### PR TITLE
76 Add formatter for JavaScript/TypeScript files

### LINKED ISSUE #76: Formatter for  typescript / javascript files
We need to add support for a formatter for typescript / javascript files similar to `black` formatter used for Python files.

### PR DESCRIPTION
**Pull request by bryannho**
## Describe your changes
- added config to enable eslint

## Issue number

Closes #76 

## Checklist before requesting a review

- [ ] Performed a self-review of my code
- [ ] Formatted my code with [`pkgmt format`](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#linting-formatting)
- [ ] Added [tests](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#testing) (when necessary).
- [ ] Added [docstring](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#documenting-changes-and-new-features) documentation and update the [changelog](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#changelog) (when needed)

### CODE REVIEW

**Comment by bryannho** [comment]
eslint was already included in the `package.json` so I simply created a config file with `npm init @eslint/config`. If we want to use a newer version of eslint I can update it in the `package.json`

**Comment by edublancas** [comment]
can you check the CI? Looks like since we added this, now the linter is running automatically.

**Comment by bryannho** [comment]
> can you check the CI? Looks like since we added this, now the linter is running automatically.

It looks like it's running `pkgmt lint` as defined in `ci.yaml` but not eslint as I didn't modify `ci.yaml` to include that. Was this the intended behavior?

**Comment by bryannho** [comment]
the CI test failed on my first commit because of the edit I made to `tsconfig.json` but now it seems to be failing because of an issue with `widgets.ipynb`. is this related to the issue with `@jupyter-widgets/base`?

**Comment by bryannho** [comment]
@edublancas could you please review? just pinging in case you weren't notified

**Review by edublancas — APPROVED** [review]

**Pull request merged**
