### PR TITLE
broken due to api change

### LINKED ISSUE #55: broken due to api change
the "deploy notebook" button in the extension no longer works since the API endpoint has been changed due to the migration from apprunner to ECS.

cc @idomic

### PR DESCRIPTION
**Pull request by tonykploomber**
## Issue number

Closes #55 

## Checklist before requesting a review

- [ ] Performed a self-review of my code
- [ ] Formatted my code with [`pkgmt format`](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#linting-formatting)
- [ ] Added [tests](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#testing) (when necessary).
- [ ] Added [docstring](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#documenting-changes-and-new-features) documentation and update the [changelog](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#changelog) (when needed)

### CODE REVIEW

**Comment by edublancas** [comment]
I encountered the same problem, it was an issue due to the typescript version. fixed it here: https://github.com/ploomber/jupysql-plugin/pull/59

**Comment by edublancas** [comment]
you might wanna rebase (or open a new PR), in https://github.com/ploomber/jupysql-plugin/pull/60 I moved files around to improve the file layout

**Comment by tonykploomber** [comment]
@edublancas 
Now it seems to work now, I still not sure what's the root cause of that CI issue (tried cleanup npm cache, specific nodejs or typescript version). What's your observation?

**Comment by edublancas** [comment]
@tonykploomber looks like npm sometimes fails due to network issues, I'll investigate more

**Review by edublancas — APPROVED** [review]

**Pull request merged**
