### PR TITLE
basic connector widget added

### PR DESCRIPTION
**Pull request by yafimvo**
[jupysql-interactive-connection](https://github.com/ploomber/jupysql-interactive-connection) implemented as JupyterLab widget. - `ConnectorWidget`

* Allows to connect to supported DBs using UI.
* Allows to create a new connection.
* The active connection button is marked with the primary color.
* Once a connection is created, the user automatically connects to it.
* Notifies the user if the connection name already exists (connection name is the alias)
* `connections.ini` file added and stores all information
* Keyring removed for simplicity
* Delete connection added with double validation
* Databases added: DuckDB, SQLite, PostgreSQL, MySQL, MariaDB, and SnowFlake.
* Displays errors

example:
image

Original issue: #16

### CODE REVIEW

**Comment by yafimvo** [comment]
please update playwright snapshots

**Review by edublancas — CHANGES_REQUESTED** [review]
I'm not sure if this was ready for review since I didn't see a request review so I took a quick look to provide some feedback.

- I noticed that if I delete the .ini file, it's created again with duckdb and sqlite connections. I think once deleted, we should ask the user to create a new connection, instead of creating these default ones

at the beginning, it was unclear to me where the connections where coming from so perhaps we can add a little label below "select a connection" that says something like "loaded from connections.ini"

image

In jupysql, we have an alias feature, I think you could take the section name in the ini file and set the alias to the connection.e.g,

```
[something]
port=121
host=stuff
```
in this case, something becomes the alias for the connection: https://jupysql.ploomber.io/en/latest/howto.html#switch-connections

also to be consistent, we can change the label from connection name to connection alias:

image

it was unclear to understand what it means to delete a connection (I think it only deletes it from the ini file, if so, we should mention it)

image

We should find a better way to display errors. For example, I tried to open a duckdb connection and it didn't work, then I noticed the Jupyter console had some messages so I clicked on it and saw that I was missing the driver: 

image

most jupyter users don't know about the console so it'd be better if this error message is visible from the widget itself (or we can show a popup)

**Comment by yafimvo** [comment]
@edublancas Thanks for the feedback! agree with everything.

Addressing:

1. Default connections - delete / load
2. Connection name - alias
3. Delete connection instructions
4. Display error
5. Code cleanup

**Comment by edublancas** [comment]
> How do you think we should use telemetry here? via jupysql library or from the plugin?

let's put the telemetry code in jupysql.

---

please address the merging conflicts. once that's done, looks like this will be ready to merge, right?

**Comment by yafimvo** [comment]
> please address the merging conflicts. once that's done, looks like this will be ready to merge, right?

Yes. Please see if the design/logic/functionality is OK.

**Review by edublancas — APPROVED** [review]

**Pull request merged**
