### PR TITLE
Provide completions only within a SQL context

### LINKED ISSUE #6: Only autocomplete when cell starts with `%%sql`

### PR DESCRIPTION
**Pull request by rschroll**
## Describe your changes

If we're in a SQL magic cell, or to the right of a line magic, provide SQL completions.  Otherwise, don't.

## Issue number

Closes #6 

## Checklist before requesting a review

- [X] Performed a self-review of my code
- [X] Formatted my code with [`pkgmt format`](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#linting-formatting)
- [X] Added [tests](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#testing) (when necessary).
- [ ] Added [docstring](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#documenting-changes-and-new-features) documentation and update the [changelog](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#changelog) (when needed)

### CODE REVIEW

**Comment by edublancas** [comment]
hi @rschroll, thanks so much for contributing to this! this is still marked as a draft, let me know once it's ready for review!

**Comment by rschroll** [comment]
Two things perhaps blocking review:
1. Tests haven't run yet.  (I generally refuse to do code review unless tests are passing; not sure if you're the same.)
2. I haven't made any documentation or changelog updates.  Re the changelog, I wasn't sure if I should add a new version entry for the new items or not.

**Comment by edublancas** [comment]
@neelasha23 please test this to ensure it works 

@rschroll 

> Tests haven't run yet. (I generally refuse to do code review unless tests are passing; not sure if you're the same.)

yep, we do the same (review until tests pass) but if contributors run into issues getting them to pass we also help!

> I haven't made any documentation or changelog updates. Re the changelog, I wasn't sure if I should add a new version entry for the new items or not.

yes, please create a new version and add an item for the changes

**Comment by neelasha23** [comment]
I haven't been able to build this locally (and I'm facing similar issue with the `master` branch). There is some error in validating the plugin:

```
(jupysql-completion) neelashasen@192 jupysql-plugin % jupyter labextension list                     
JupyterLab v4.1.5
/Users/neelashasen/miniforge3/envs/jupysql-completion/share/jupyter/labextensions
        jupyterlab-jupytext v1.4.2 enabled OK (python, jupytext)
        ploomber-extension v0.1.0 enabled OK (python, ploomber_extension)
        jupysql-plugin v0.4.2 enabled  X (python, jupysql-plugin)
        jupyterlab_pygments v0.3.0 enabled OK (python, jupyterlab_pygments)
        @jupyter-widgets/jupyterlab-manager v5.0.10 enabled OK (python, jupyterlab_widgets)


   The following extensions are outdated:
        jupysql-plugin
        
   Consider checking if an update is available for these packages.

(jupysql-completion) neelashasen@192 jupysql-plugin % jupyter labextension enable jupysql_plugin
(jupysql-completion) neelashasen@192 jupysql-plugin % jupyter server extension list
Config dir: /Users/neelashasen/.jupyter

Config dir: /Users/neelashasen/miniforge3/envs/jupysql-completion/etc/jupyter
    jupysql_plugin enabled
    - Validating jupysql_plugin...
       X validation failed
    jupyter_lsp enabled
    - Validating jupyter_lsp...
      jupyter_lsp 2.2.4 OK
    jupyter_server_terminals enabled
    - Validating jupyter_server_terminals...
      jupyter_server_terminals 0.5.3 OK
    jupyterlab enabled
    - Validating jupyterlab...
```

I have added manually as well by running 
```
jupyter labextension list
jupyter server extension list
```

I have run `git clean -fdx` and created clean environments multiple times but I see the error everytime. Still trying to get this work @edublancas

**Review by edublancas — APPROVED** [review]

**Comment by edublancas** [comment]
thanks @rschroll, making a release now!

**Pull request merged**
